research_task:
  description: >
    Research current trends, developments, and interesting aspects about {topic}.
    Focus on finding content that would be engaging for LinkedIn posts.
    Include innovative ideas, industry trends, and thought-provoking insights.
    Make sure to find at least 5 different aspects or angles that could be turned into LinkedIn posts.
  expected_output: >
    A list of 5 interesting aspects about {topic}, each with a brief explanation of why it would make
    a good LinkedIn post. Format as bullet points.
  agent: researcher

reporting_task:
  description: >
    Transform the research findings into 5 engaging LinkedIn posts. Write in this language: {language} and avoid these words: {avoid_words}.
    Address the reader {address}.
    Refer to yourself as {perspective}.
    For each point:
    1. Create an attention-grabbing title with a bit clickbait and two fitting emojis
    2. Write compelling, unconventional post content (at least 10 sentences with 2 lines breaks after each sentence).
    3. Use short sentences and simple language. 
    4. Make it a very {mood} post.
    5. Structure the post in a way that is easy to read and understand.
    6. Write without a CTA. 
    7. Format the output as a JSON object with 'posts' array containing 'titel' and 'text' for each post
  expected_output: >
    A JSON object containing exactly 5 LinkedIn posts, each with a title and content
  agent: reporting_analyst